name: my_notes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.8
  firebase_core: ^2.27.0
  flutter:
    sdk: flutter
  path_provider: ^2.1.4
  share_plus: ^7.2.2
  provider: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
