// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8qaNOV_VsLm78NNF9K4hG_QRmgil742E',
    appId: '1:99487972621:web:9c23b19f62417111688444',
    messagingSenderId: '99487972621',
    projectId: 'my-notes-daily',
    authDomain: 'my-notes-daily.firebaseapp.com',
    storageBucket: 'my-notes-daily.appspot.com',
    measurementId: 'G-Z50VGNLG92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmgZwbOcKJZOMbPrnQPVoThnqKKelPUb4',
    appId: '1:99487972621:android:aa63f82a3f401156688444',
    messagingSenderId: '99487972621',
    projectId: 'my-notes-daily',
    storageBucket: 'my-notes-daily.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeFSR84b7mJT6X7gQ0xjqVyzOneXtbStc',
    appId: '1:99487972621:ios:380c86e41eeeae0b688444',
    messagingSenderId: '99487972621',
    projectId: 'my-notes-daily',
    storageBucket: 'my-notes-daily.appspot.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeFSR84b7mJT6X7gQ0xjqVyzOneXtbStc',
    appId: '1:99487972621:ios:380c86e41eeeae0b688444',
    messagingSenderId: '99487972621',
    projectId: 'my-notes-daily',
    storageBucket: 'my-notes-daily.appspot.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8qaNOV_VsLm78NNF9K4hG_QRmgil742E',
    appId: '1:99487972621:web:d34c333567ac3db5688444',
    messagingSenderId: '99487972621',
    projectId: 'my-notes-daily',
    authDomain: 'my-notes-daily.firebaseapp.com',
    storageBucket: 'my-notes-daily.appspot.com',
    measurementId: 'G-HJDS41W2RQ',
  );
}
